spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.JdbcClientAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3306/sparta
    username: root
    password: woqkfrmq12
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        type: true
    open-in-view: false
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE